version: "3.4"

services:
  web:
    build: .
    container_name: web
    volumes:
      - .:/var/www
      - ./docker-entry.sh:/etc/entrypoint.sh
    entrypoint: [ "sh", "/etc/entrypoint.sh" ]
    ports:
      - "3310:3310"