version: "3.4"

services:
  client:
    build: ./client
    container_name: docker_client
    ports:
      - 3000:3000
    volumes:
        - ./client:/usr/src/app
        - /usr/src/app/node_modules

  server:
    build: ./server
    container_name: docker_server
    ports:
      - 3310:3310
    volumes:
        - ./server:/server
